### ISSUE TITLE
Not Compatible With Latest ActiveRecord

### ISSUE THREAD

**Issue by timscott** [ConsultingMD/graphql-preload#1]
Currently, I'm not able to use this gem without downgrading Rails which I cannot really do.

```
    graphql-preload was resolved to 1.0.1, which depends on
      activerecord (<= 5, >= 3.2)

    rails (~> 5.1.2) was resolved to 5.1.2, which depends on
      activerecord (= 5.1.2)
```

Is there are reason to limit to `activerecord <= 5`?

**Comment by etripier** [comment]
Nope, no reason. I'll change it to `activerecord <= 6`.

**Comment by etripier** [comment]
@timscott Try the latest version of the gem (`v1.0.2`). Let me know if that fixes your issue!

**Comment by timscott** [comment]
Working. Thanks for letting me to my favorite kind of coding: deleting code from my app!
