### ISSUE TITLE
Class based Schema definition supported?

### ISSUE THREAD

**Issue by ardias** [ConsultingMD/graphql-preload#13]
Hi there,
I'm trying to use this gem in a GraphQL api that is using class base definition and I can't seem to make it work (I'm a ruby newbie). I added the gem to the Gemfile and ran `bundle`.
Defined my Schema as:
 
```
 class ApiSchema < GraphQL::Schema
    use GraphQL::Batch
    enable_preloading
 end
```

The problem is `enable_preloading` gets me a `undefined local variable or method `enable_preloading'. `
I tried `require grapqhl/preload `on top of the file;

I tried `GraphQL::Preload::SchemaMethods.enable_preloading` but i get` uninitialized constant GraphQL::Preload::SchemaMethods`.

Any idea?

**Comment by mareczek** [comment]
+1

**Comment by modosc** [comment]
looks like it was added [here](https://github.com/ConsultingMD/graphql-preload/commit/265dd7fdf263e3f26ceea27abc7dc4fd44a48f6d) but i can't quite figure out the syntax for the class-based api.

**Comment by modosc** [comment]
figured it out - it works fine like so:
```
field :foo, Types::Bar, preload: [:a, :b, :c]
```
but with the upgrade the non-class based version doesn't work. our codebase is still in transition so i was getting errors from those.

**Comment by mengqing** [comment]
@ardias You'll need to include the module first

```
include GraphQL::Preload::SchemaMethods

class ApiSchema < GraphQL::Schema
   use GraphQL::Batch
   enable_preloading
end
```

**Comment by ardias** [comment]
Thanks everyone for the tips. I'll try it out and let you know how it goes.

**Comment by ardias** [comment]
So i got it working +/-. I don't get the 'undefined variable or method' errors, and i managed to get at least one of the associations working. In another case it failed with "method `object` not defined in class `whatever`", but this probably my code.

Anyway, it would be cool to have some examples using class-based API, if you can manage.
Thanks

**Comment by prasannshah** [comment]
`instrument(:field, GraphQL::Preload::Instrument.new)`

**This works**. Basically instead of calling `enable_preloading` which is defined by extending schema methods, just call instrument directly. 

> Just a side note. It seems to work for me in 2.0.1 version. It is failing in 2.1.0 somehow with the error. GraphQL::Define::NoDefinitionError (GraphQL::Field can't define 'preload'):
