### ISSUE TITLE
Aggregate Functions Supported?

### ISSUE THREAD

**Issue by timscott** [ConsultingMD/graphql-preload#2]
I have a type like this:

```ruby
Types::Design = GraphQL::ObjectType.define do
  # other fields
  field :ordersCount, types.Int do
    preload :orders
    resolve -> (design, _args, _context) {design.orders.count}
  end
end
```

My class:

```ruby 
class Design < ApplicationRecord
  has_many :order_items
  has_many :orders, -> {distinct}, through: :order_items
  # ...
end
```

This produces an n+1 condition, issuing a query for each Design, like:

```ruby
# abbreviated
SELECT COUNT(DISTINCT "orders"."id") FROM "orders" ... where ... "order_items"."design_id" = $1  [["design_id", 46]]
```

If I change the resolver from `design.orders.count` to `design.orders.size`, then the n+1 goes away. However, I'm assuming that will load and hydrate all of the orders and count them in memory. I'm not sure which is better or worse, but neither is good.

Is it possible to add support for preloading with aggregate SQL functions like `count`?

**Comment by etripier** [comment]
Hey Tim, that's a good question. I'll try to take a stab at it this weekend.

**Comment by etripier** [comment]
Unfortunately, I can't find an easy way to preload aggregate queries (at least, using the `ActiveRecord::Associations::Preloader`). It looks like it'll populate the `target` property of the association with the preloaded records, but it doesn't provide any easy chainable methods to perform aggregate queries.

Calling `#size` might be your best bet, but you're right that it's not ideal. `design.orders` will reference the `target` of the preloaded association, so you're not burning too much extra memory, but it certainly is nicer to get your SQL engine to do the work for you.

The most popular technique for dealing with this seems to be creating custom views to handle aggregate queries. There is a gem that will do this for you:
https://github.com/clio/jit_preloader#loading-aggregate-methods-on-associations

You can also implement a `counter_cache` column:
http://edgeguides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache

Sorry! I was hoping I could find a simple way to solve this problem, but it's a bit tougher than I thought it would be. Hope the links above help a bit.
