### ISSUE TITLE
Offering help in gem maintenance

### ISSUE THREAD

**Issue by Envek** [ConsultingMD/graphql-preload#30]
Hi, everyone who contributed to this gem: @ConsultingMD, @RoryO, @etripier.

Even though this gem is quite small and its functionality can be kind of easily implemented in an application, it is very convenient to use and (as a sign of that) is still in demand in the community, as can be seen by the number of issues and pull requests.

However, it seems that it lacks support as there is a number of excellent pull requests that awaiting merging for more than a year and issues not being answered.

I tried to migrate from this gem to just using graphql-batch directly and didn't like the experience (and amount of boilerplate code I had to write).

So, instead of stopping using it, I want to offer my help in graphql-preload maintenance to be able to continue using it in projects I'm working on.

What I can do (and what I'm actually planning to do):
 - keep it in working condition for new versions of GraphQL-Ruby and ActiveRecord.
 - write and maintain test suite (there is already starting point for it at https://github.com/ConsultingMD/graphql-preload/pull/14)
 - set up CI with build matrix
 - review current and future pull requests from time to time and accept relevant ones
 - respond to all current and future issues from time to time and fix bugs that are relatively easy to fix
 - publish releases with fixes and features according to SemVer

What I'm not planning to do:
 - add new features (unless someone will write pull request and convince me that feature is useful)
 - move or rename it
 - add any malicious code (it should be obvious, but too many precedents lately)

What I need for it:
 - push access to source code repository: https://github.com/ConsultingMD/graphql-preload
 - push access to rubygems: https://rubygems.org/gems/graphql-preload

Who am I?

My name is Andrey, and I'm working at [Evil Martians](https://evilmartians.com/). Martians use, create, and maintain open-source software themselves and encourages others to do so. However, here I offer my help as an individual.
I've authored a bunch of small gems: [`after_commit_everywhere`](https://github.com/Envek/after_commit_everywhere/), [`evil-seed`](https://github.com/evilmartians/evil-seed), [`yabeda`](https://github.com/yabeda-rb), and others.

What do you think?

**Comment by RoryO** [comment]
Thanks Andrey. Neither I or Etienne are affiliated with this anymore so unfortunately we are not of any help.

**Comment by cobbr2** [comment]
Hi, Andrey. I just saw this conversation, and as a staff sw engineer at Grand Rounds (aka ConsultingMD) I'd like to welcome your help.  I'm just getting my feet wet on this part of our code, so can't make a commitment today, but thought I'd reach out to say "yes, we'll figure something out here".  And I'd like to especially thank you for the testing PR; I haven't examined it in depth yet, but I'm super happy to see it.  And thanks, @RoryO for keeping the conversation going, we miss you.

**Comment by Fleick** [comment]
If there are some people here to support this gem, would it be possible to fork the project and deploy it under a similar name using rubygems? The functionality this gem offers is in my opinion definitely worth to be preserved and I would like to keep using it in our project. Unfortunately, due to the switch to Rails 6, the decision has to be made to either kick the gem out or continue using it. But a further development with and an expansion of the usage is simply nonsensical if the gem is no longer supported and therefore compatibility problems are to be expected in the foreseeable future.

Since the author of the gem hasn't answered this ticket for about 2 months and the ticket for the general Rails 6 support hasn't been answered for more than 4 months, we shouldn't expect further support from this site.

**Comment by Envek** [comment]
@Fleick, you can use my fork (we're using it in one of our projects with Rails 6 and GraphQL-Ruby 1.10) while discussion is going here:
```ruby
gem "graphql-preload", git: "https://github.com/Envek/graphql-preload"
```
I want to avoid publishing under other name if possible (because naming is hard).

**Comment by severin** [comment]
@cobbr2 @Envek any updates on this? I would love to have an official release supporting graphql 1.10...

**Comment by wyattEpp** [comment]
@Envek - we'd like to offer you the option to take complete ownership of this gem. With our org's move away from Rails services for GraphQL, we have not been able to allocate appropriate time to maintain this gem.

If you are interested, please send an email to @wyattEpp and we will coordinate a swap to your fork.

**Comment by Envek** [comment]
@wyattEpp thank you! Sent an email to the address specified in your GitHub profile. :incoming_envelope:

**Comment by rkorzeniec** [comment]
@wyattEpp are you still planning to transfer the ownership to @Envek ?
