### ISSUE TITLE
Detect and warn to preloading

### ISSUE THREAD

**Issue by eshaiju** [ConsultingMD/graphql-preload#6]
Is there any way we can auto detect and add a warning logger to add eager loading just like bullet gem do?
This could be nice feature to have

**Comment by etripier** [comment]
@eshaiju That's a great suggestion, but I think it might be out of scope for this gem. Like you mentioned, Bullet is very capable of detecting n + 1 queries - duplicating that functionality here would add a lot of complexity without significant benefit (at least, not if you're already using Bullet). What do you think?

**Comment by eshaiju** [comment]
@etripier If bullet gem is showing it then there is no need to implement here. But as per my experiments bullet gem not picking GraphQL N+1 queries. Did you check it?
![screen shot 2017-10-18 at 11 22 59 pm](https://user-images.githubusercontent.com/2918256/31734135-55165c62-b45b-11e7-9da9-df4d5083a8e0.png)

**Comment by etripier** [comment]
@eshaiju I haven't tried it just yet. I saw you raised the issue at https://github.com/flyerhzm/bullet/issues/364 - would you let me know how that turns out?
